import sqlite3

DB = "/app/data/provence_callian.db"

prospects = [
    {
        "date": "2026-04-03",
        "nom": "Laurent et Sophie Maréchal",
        "mail": "laurent.marechal83@gmail.com",
        "telephone": "06 12 34 87 21",
        "domicile": "Draguignan",
        "bien": "Appartement",
        "villes": "Callian, Fayence, Montauroux",
        "quartiers": "",
        "budget_max": 220000,
        "criteres": "3 pièces minimum, lumineux, calme, proche commodités",
        "etat": "Bon état ou rénové",
        "expo": "Sud",
        "stationnement": "1 place minimum",
        "copro": "Oui accepté si charges raisonnables",
        "exterieur": "Terrasse ou balcon souhaitée",
        "etage": "Pas rez-de-chaussée",
        "destination": "Résidence principale",
        "observation": "Premier achat. Veulent quitter la location à Draguignan. Disponibles rapidement. Préfèrent les petits immeubles.",
    },
    {
        "date": "2026-04-07",
        "nom": "Michel Fontaine",
        "mail": "mfontaine.var@orange.fr",
        "telephone": "06 78 45 12 03",
        "domicile": "Marseille 8e",
        "bien": "Maison de village",
        "villes": "Callian, Saint-Paul-en-Forêt, Bargemon",
        "quartiers": "Centre village",
        "budget_max": 200000,
        "criteres": "Charme provençal, pierre apparente, au moins 3 chambres",
        "etat": "À rénover accepté si bonne structure",
        "expo": "Indifférent",
        "stationnement": "Garage ou parking privatif",
        "copro": "Non",
        "exterieur": "Cour ou terrasse",
        "etage": "Indifférent",
        "destination": "Résidence secondaire",
        "observation": "Retraité, cherche pied-à-terre en Provence pour futur déménagement. Visite uniquement les week-ends. Très motivé sous 300k.",
    },
    {
        "date": "2026-04-10",
        "nom": "Famille Bertrand-Nguyen",
        "mail": "c.bertrand.immo@gmail.com",
        "telephone": "07 56 89 23 41",
        "domicile": "Paris 15e",
        "bien": "Villa",
        "villes": "Callian, Tourrettes, Fayence",
        "quartiers": "",
        "budget_max": 680000,
        "criteres": "5 pièces+, grand jardin, piscine ou possibilité, vue dégagée",
        "etat": "Bon état ou récent",
        "expo": "Sud ou Sud-Ouest",
        "stationnement": "Garage double ou grand parking",
        "copro": "Non",
        "exterieur": "Jardin indispensable, piscine idéale",
        "etage": "Plain-pied préféré",
        "destination": "Résidence principale",
        "observation": "Télétravail total, veulent s'installer définitivement dans le Var d'ici septembre. 3 enfants. Chien. Budget peut évoluer si coup de cœur.",
    },
    {
        "date": "2026-04-12",
        "nom": "Isabelle Roux",
        "mail": "isabelle.roux.invest@gmail.com",
        "telephone": "06 31 77 88 55",
        "domicile": "Nice",
        "bien": "Studio, Appartement",
        "villes": "Callian, Fréjus, Bagnols-en-Forêt",
        "quartiers": "",
        "budget_max": 155000,
        "criteres": "Petit surface rentable, proche commerces, bien entretenu",
        "etat": "Bon état",
        "expo": "Indifférent",
        "stationnement": "Pas indispensable",
        "copro": "Oui",
        "exterieur": "Pas nécessaire",
        "etage": "Indifférent",
        "destination": "Investissement locatif",
        "observation": "Investisseuse déjà propriétaire de 2 biens à Nice. Cherche à diversifier dans l'arrière-pays varois. Financement déjà validé par la banque.",
    },
    {
        "date": "2026-04-15",
        "nom": "Pierre et Anne-Laure Deschamps",
        "mail": "pierre.deschamps.83@gmail.com",
        "telephone": "06 44 22 91 67",
        "domicile": "Toulon",
        "bien": "Terrain",
        "villes": "Callian, Tourrettes, Montauroux",
        "quartiers": "",
        "budget_max": 260000,
        "criteres": "Terrain constructible, viabilisé ou viabilisable, vue ou nature",
        "etat": "",
        "expo": "Sud obligatoire",
        "stationnement": "",
        "copro": "Non",
        "exterieur": "",
        "etage": "",
        "destination": "Construction résidence principale",
        "observation": "Architecte contacté, projet de maison bioclimatique 130m². Veulent terrain entre 1000 et 2500m². Projet sérieux, achat si terrain trouvé avant fin 2026.",
    },
    {
        "date": "2026-04-18",
        "nom": "Nathalie Germain",
        "mail": "nathalie.germain.fayence@gmail.com",
        "telephone": "06 99 14 37 82",
        "domicile": "Fayence",
        "bien": "Maison, Maison de village",
        "villes": "Fayence, Callian, Saint-Paul-en-Forêt",
        "quartiers": "",
        "budget_max": 420000,
        "criteres": "4 chambres minimum, bureau, jardin, lumineux",
        "etat": "Bon état",
        "expo": "Sud ou Est",
        "stationnement": "Garage",
        "copro": "Non",
        "exterieur": "Jardin avec espace repas extérieur",
        "etage": "Indifférent",
        "destination": "Résidence principale",
        "observation": "Divorcée, vend sa maison actuelle à Fayence. Budget confirmé. Cherche plus grand pour accueillir ses 4 enfants les week-ends. Urgente — doit trouver avant la rentrée de septembre.",
    },
    {
        "date": "2026-04-22",
        "nom": "Julien Morin",
        "mail": "julien.morin.pro@hotmail.fr",
        "telephone": "07 83 56 12 09",
        "domicile": "Sophia Antipolis",
        "bien": "Appartement",
        "villes": "Callian, Mandelieu-la-Napoule, Saint-Raphaël",
        "quartiers": "",
        "budget_max": 420000,
        "criteres": "3-4 pièces, parking, résidence sécurisée, bon DPE",
        "etat": "Récent ou rénovation faite",
        "expo": "Sud",
        "stationnement": "Box ou parking sécurisé",
        "copro": "Oui",
        "exterieur": "Terrasse ou balcon indispensable",
        "etage": "À partir du 2e",
        "destination": "Résidence principale",
        "observation": "Ingénieur en tech, célibataire, premier achat. Préapproval bancaire à 420k. Peut se décider vite. Veut un logement clé en main.",
    },
    {
        "date": "2026-04-25",
        "nom": "Robert et Claudette Pagnol",
        "mail": "rpagnol.retraite@gmail.com",
        "telephone": "06 17 43 98 26",
        "domicile": "Lyon 6e",
        "bien": "Maison",
        "villes": "Bargemon, Saint-Paul-en-Forêt, Vidauban",
        "quartiers": "",
        "budget_max": 300000,
        "criteres": "Plain-pied ou peu de marches, 3 chambres, environnement calme",
        "etat": "Bon état",
        "expo": "Indifférent",
        "stationnement": "Garage ou abri voiture",
        "copro": "Non",
        "exterieur": "Jardin facile d'entretien",
        "etage": "Plain-pied fortement préféré",
        "destination": "Résidence principale",
        "observation": "Retraités en bonne santé, 68 et 65 ans. Veulent finir leur vie en Provence. Vendent leur appartement à Lyon (estimation 480k). Très sérieux.",
    },
    {
        "date": "2026-04-28",
        "nom": "Thomas Vidal",
        "mail": "thomas.vidal.83@gmail.com",
        "telephone": "06 62 38 74 11",
        "domicile": "Bagnols-en-Forêt",
        "bien": "Appartement",
        "villes": "Bagnols-en-Forêt, Callian, Fréjus",
        "quartiers": "",
        "budget_max": 165000,
        "criteres": "2-3 pièces, calme, pas trop de charges",
        "etat": "Correct",
        "expo": "Indifférent",
        "stationnement": "1 place",
        "copro": "Oui accepté",
        "exterieur": "Balcon apprécié",
        "etage": "Indifférent",
        "destination": "Résidence principale",
        "observation": "Travaille à Fréjus, veut se rapprocher mais rester dans le coin. Loue actuellement à Bagnols. Primo-accédant, PTZ envisagé.",
    },
    {
        "date": "2026-05-02",
        "nom": "Éric et Madeleine Carvalho",
        "mail": "eric.carvalho.immo@gmail.com",
        "telephone": "06 88 12 54 33",
        "domicile": "Cannes",
        "bien": "Villa, Maison",
        "villes": "Callian, Montauroux, Bagnols-en-Forêt",
        "quartiers": "",
        "budget_max": 640000,
        "criteres": "Grande villa, au moins 5 pièces, piscine, discrétion, vue",
        "etat": "Bon état ou récent",
        "expo": "Sud ou Ouest",
        "stationnement": "Double garage",
        "copro": "Non",
        "exterieur": "Piscine indispensable, jardin arboré",
        "etage": "Indifférent",
        "destination": "Résidence principale",
        "observation": "Chef d'entreprise, veut quitter Cannes pour plus de tranquillité. Femme et 2 enfants adultes. Budget ferme à 640k. Très discret, contact uniquement par mail en première approche.",
    },
]

conn = sqlite3.connect(DB)
cur = conn.cursor()

for p in prospects:
    cur.execute("""
        INSERT INTO prospects
        (date, nom, mail, telephone, domicile, bien, villes, quartiers,
         budget_max, criteres, etat, expo, stationnement, copro,
         exterieur, etage, destination, observation)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    """, (
        p["date"], p["nom"], p["mail"], p["telephone"], p["domicile"],
        p["bien"], p["villes"], p["quartiers"], p["budget_max"],
        p["criteres"], p["etat"], p["expo"], p["stationnement"],
        p["copro"], p["exterieur"], p["etage"], p["destination"],
        p["observation"],
    ))
    print(f"  ✓ {p['nom']}")

conn.commit()
conn.close()
print(f"\n✓ {len(prospects)} prospects insérés dans {DB}")
